name: py36
channels:
  - conda-forge
  - defaults
dependencies:
  - ffmpeg-python=0.2.0
  - pip=21.0.1
  - python=3.6.6
  - pip:
    - chardet==4.0.0
    - dateutils==0.6.12
    - idna==2.10
    - lxml==4.6.3
    - podgen==1.1.0
    - python-dateutil==2.8.1
    - pytz==2021.1
    - requests==2.25.1
    - six==1.15.0
    - tinytag==1.5.0
    - urllib3==1.26.4
